basic:
    name: 'https://partners-cap.com'
    environments:
        production: 'https://partners-cap.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 960
        - 1200
    pages:
        - /
        - /contact
        - /about-us
        - /about-us/our-history
        - /our-team/meet-the-board
        - /our-team/meet-the-shareholders
        - /our-team
        - /who-we-work-with
        - /research
        - /research/investment-philosophy
        - /about-us/careers
        - /about-us/diversity-equity-and-inclusion
        - /press-archive
        - /who-we-work-with/endowments-foundations
        - /who-we-work-with/private-clients
        - /who-we-work-with/institutions
        - /ocio-solution
        - /private-markets-mandates
        - /investment-approach
        - /investments/asset-classes/liquid-credit
        - /investments/asset-classes/private-debt
        - /investments/asset-classes/uncorrelated-alternatives
        - /investments/asset-classes/absolute-return
        - /investments/asset-classes/public-equities
        - /investments/asset-classes/private-equity
        - /investments/asset-classes/real-estate
        - /investments/asset-classes/co-investments
        - /investment-approach/sustainable-investing
        - /asset-managers
        - /asset-managers/manager-due-diligence
        - /partners-capital-san-francisco
        - /partners-capital-new-york
        - /partners-capital-boston
        - /partners-capital-london
        - /partners-capital-paris
        - /partners-capital-asia-pacific
        - /regulatory-disclosures
        - /mifid-ii-best-execution
        - /form-adv
    monitoring:
        days: {  }
        type: daily
        schedule_time: '01:30 PM'
        schedule_time_zone: Europe/London
        compare_with: baseline
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
